spring:
  data:
    mongodb:
 #     authentication-database:
    #  username: ${MONGO_USERNAME}
    # password: ${MONGO_PASSWORD}
      database: keepMongo
      port: 8086
      host: localhost
  application:
    name: category-service
server:
  port: 8083
